### ISSUE TITLE
Use of "oneOf" is not working properly

### ISSUE THREAD

**Issue by Cry0nicS** [horiuchi/dtsgenerator#513]
Given a basic schema like
```yaml
ParticipantInfo:
    title: ParticipantInfo
    type: object
    allOf:
        - $ref: "participant.yaml#/GeneralFields"
        - oneOf:
            - $ref: "team.yaml#/TeamInfo"
            - $ref: "../player.yaml#/PlayerInfo"
```
Will result in a JSON like this:
```json
"ParticipantInfo": {
	"title": "ParticipantInfo",
	"type": "object",
	"allOf": [
		{
			"$ref": "#/components/schemas/GeneralFields"
		},
		{
			"oneOf": [
				{
					"$ref": "#/components/schemas/TeamInfo"
				},
				{
					"$ref": "#/components/schemas/PlayerInfo"
				}
			]
		}
	]
},


"GeneralFields": {
	"title": "GeneralFields",
	"type": "object",
	"discriminator": {
		"propertyName": "type"
	},
	"properties": {
		"id": {
			"type": "integer",
			"format": "int32"
		},
		"countryCode": {
			"type": "integer"
		},
		"type": {
			"type": "string",
			"description": "The participant type\n\n```\n0 = Player\n1 = Team\n```\n"
		}
	}
},

"TeamInfo": {
	"title": "TeamInfo",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"imageName": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"team": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"tag": {
					"type": "string"
				}
			}
		}
	}
}

"PlayerInfo": {
	"title": "PlayerInfo",
	"type": "object",
	"allOf": [
		{
			"$ref": "#/components/schemas/UserInfo"
		},
		{
			"properties": {
				"id": {
					"type": "integer"
				},
				"imageName": {
					"type": "string"
				}
			}
		}
	]
}
```

Generating types for this JSON results in the following (basically, without the fields `GeneralFields` that should be coming from `allof`)

```ts
/**
 * ParticipantInfo
 */
export type ParticipantInfo =
	/* ParticipantInfo */ /* TeamInfo */
		| TeamInfo
		| /* PlayerInfo */ PlayerInfo;
```

Using _just_ `oneOf` or `allOf` results in the corresponding types being correctly generated. Thus, I believe the issue is related to `oneOf` in conjunction with `allOf`
