### ISSUE TITLE
If there are 8s and 9s, they will be zero-suppressed.

### ISSUE THREAD

**Issue by Vivi-Ornitier** [horiuchi/dtsgenerator#540]
008 and 009 (also 018, 019, and more...) they will be zero-suppressed.

Example:
**input yaml**
```
type: object
properties:
  foo:
    description: "example"
    type: "string"
    enum: ['001','002','003','004','005','006','007','008','009','010']
    example: "001"
```

**output .d.ts**
```
/**
     * example
     * example:
     * 001
     */
    foo?:
      | "001"
      | "002"
      | "003"
      | "004"
      | "005"
      | "006"
      | "007"
      | "8"
      | "9"
      | "010";
```

This issue seems to have occurred since 3.7.1.
